---
dataset_mode: pair

checkpoints: './checkpoints'
model_name: &MODEL_NAME test
model_class: Diff_MPR
resume_train: false 
which_epoch: latest
start_epoch: 0
save_iter: 100
display_freq: 10
val_freq: 100
patch_size: 256
gpu: [0,1]
input_nc: 3
output_nc: 3
init_type: xavier
init_gain: 0.02
epoch: 40
# batch_size: 4
is_training: true
load_only_G: false
Distributed: &Dist false

train:
  lr_G: 0.0001
  beta1: 0.9
  optimizer: adam
  scheduler: linear

datasets:
  train:
    degrade_num: 4
    data_len: -1
    dataroot_blur: '/home/yjz/hdd/deblur_datasets/Deblur_whole/train_patch' # path to training data
    dataroot_rain: '/home/yjz/hdd/derain_datasets/Derain_whole/train_patch' 
    dataroot_noise: '/home/yjz/hdd/denoise_datasets/Denoise_whole/train_patch' 
    dataroot_light: '/home/yjz/hdd/lowlight_datasets/Lowlight_whole/train_patch' 
    patch_size: 256
    batch_size: 1
    num_workers: 4
    use_shuffle: true
    Distributed: *Dist 
  val:
    data_len: 2
    dataroot_blur: '/home/yjz/hdd/deblur_datasets/Deblur_whole/test/GOPRO'    # path to validation data
    dataroot_rain: '/home/yjz/hdd/derain_datasets/Derain_whole/test/Rain100L'    
    dataroot_noise: '/home/yjz/hdd/denoise_datasets/Denoise_whole/test/SIDD'    
    dataroot_light: '/home/yjz/hdd/lowlight_datasets/Lowlight_whole/test'    
    patch_size: -1

model:
  g_name: MPRNet_MH
  pretrain_G: '/home/yjz/Diffusion/Multitask_restore/checkpoints/MPR/MPR_DAlayer_AttnSum/G_net_best.pth'
  n_feat: 48 
  degrade_num: 4 
  use_type_emb: True
  diffusion:
     d_name: sr3
     in_channel: 9
     out_channel: 3
     loss_type: l1
     beta_schedule:
      schedule: linear
      n_timestep: 1000
      linear_start: 1.0e-6
      linear_end: 1.0e-2
  use_sigmoid: 0
  norm: 

diff_sample:
  sample_type: generalized #ddpm or generalized
  skip_type: uniform
  n_timestep: 1000
  sample_step: 10

test:
  result_dir: ./exp_results
  save_dir: *MODEL_NAME
  verbose: True
  test_batch_size: 1
  which_epoch: best
  dataset_mode: pair
  dataset:
    batch_size: 1
    data_len: -1
    degrade_type: blur
    dataroot: '/home/yjz/hdd/deblur_datasets/Deblur_whole/test/'    # path to validation data
    patch_size: -1




