---
dataset_mode: mix

checkpoints: './checkpoints/Diff'
model_name: &MODEL_NAME MPR
MPR_model: './pretrain_models/MPRnet/model_deblurring.pth'
model_class: Diff_MPR
resume_train: False 
which_epoch: latest
start_epoch: 0
save_epoch: 50
crop_size: 256
gpu: [0]
input_nc: 3
output_nc: 3
init_type: xavier
init_gain: 0.02
epoch: 1000
batch_size: 2
is_training: False
iteration_G: 1
load_only_G: false
Distributed: false

train:
  lr_G: 0.0001
  beta1: 0.9
  optimizer: adam
  scheduler: linear
  dataroot_blur: '/home/yjz/hdd/deblur_datasets/Deblur_whole/train_patch' # path to training data
  dataroot_rain: '/home/yjz/hdd/derain_datasets/Derain_whole/train_patch' 
  dataroot_noise: '/home/yjz/hdd/denoise_datasets/Denoise_whole/train_patch' 
  dataroot_light: '/home/yjz/hdd/lowlight_datasets/Lowlight_whole/train_patch' 
  

val:
  val_batch_size: 1
  verbose: False
  data_len: 50
  dataroot_blur: '/home/yjz/hdd/deblur_datasets/Deblur_whole/test/GOPRO'    # path to validation data
  dataroot_rain: '/home/yjz/hdd/derain_datasets/Derain_whole/test/Rain100L'    
  dataroot_noise: '/home/yjz/hdd/denoise_datasets/Denoise_whole/test/SIDD'    
  dataroot_light: '/home/yjz/hdd/lowlight_datasets/Lowlight_whole/test'    

model:
  g_name: MPRNet_MH
  pretrain_G: 
  n_feat: 48
  degrade_num: 4 
  use_type_emb: true
  diffusion:
     d_name: sr3
     in_channel: 9
     out_channel: 3
     loss_type: l1
     beta_schedule:
      schedule: linear
      n_timestep: 1000
      linear_start: 1.0e-6
      linear_end: 1.0e-2
  use_sigmoid: 0
  norm: 

diff_sample:
  sample_type: ddim #ddpm or ddim
  skip_type: uniform
  n_timestep: 1000
  sample_step: 100


test:
  result_dir: ./exp_results/Diff
  save_dir: *MODEL_NAME
  verbose: True
  test_batch_size: 1
  which_epoch: latest
  dataset_mode: pair
  multi_step: false
  continous: False
  dataset:
    batch_size: 1
    data_len: -1
    degrade_type: rain
    dataroot: '/home/yjz/hdd/derain_datasets/Derain_whole/test/'    # path to validation data
    patch_size: -1
  # test_dir: '/home/yjz/Image_deblur/Multitask_restore/exp_results/Mix_blur_noise/mixed/Gopro_gauss'   
