---
dataset_mode: mix

checkpoints: './checkpoints/MPR'
model_name: &MODEL_NAME MPR_baseline
MPR_model: './pretrain_models/MPRnet/model_deblurring.pth'
model_class: MPRnet
resume_train: False 
which_epoch: latest
start_epoch: 0
save_epoch: 50
crop_size: 256
gpu: [0,1]
input_nc: 3
output_nc: 3
init_type: xavier
init_gain: 0.02
epoch: 1000
batch_size: 2
is_training: False
iteration_G: 1
load_only_G: false
Distributed: false

train:
  lr_G: 0.0001
  beta1: 0.9
  optimizer: adam
  scheduler: linear
  dataroot_blur: '/home/yjz/hdd/deblur_datasets/Deblur_whole/train_patch' # path to training data
  dataroot_rain: '/home/yjz/hdd/derain_datasets/Derain_whole/train_patch' 
  dataroot_noise: '/home/yjz/hdd/denoise_datasets/Denoise_whole/train_patch' 
  dataroot_light: '/home/yjz/hdd/lowlight_datasets/Lowlight_whole/train_patch' 
  

val:
  val_batch_size: 1
  verbose: False
  data_len: 50
  dataroot_blur: '/home/yjz/hdd/deblur_datasets/Deblur_whole/test/GOPRO'    # path to validation data
  dataroot_rain: '/home/yjz/hdd/derain_datasets/Derain_whole/test/Rain100L'    
  dataroot_noise: '/home/yjz/hdd/denoise_datasets/Denoise_whole/test/SIDD'    
  dataroot_light: '/home/yjz/hdd/lowlight_datasets/Lowlight_whole/test'    

model:
  g_name: MPRnet
  d_name: Offset
  use_sigmoid: 0
  norm: 


test:
  result_dir: ./exp_results
  save_dir: *MODEL_NAME
  verbose: True
  test_batch_size: 1
  which_epoch: latest
  dataset_mode: pair
  dataset:
    batch_size: 1
    data_len: -1
    degrade_type: rain
    dataroot: '/home/yjz/hdd/derain_datasets/Derain_whole/test/Test1200'    # path to validation data
    patch_size: -1
  # test_dir: '/home/yjz/Image_deblur/Multitask_restore/exp_results/Mix_blur_noise/mixed/Gopro_gauss'   
