---
dataset_mode: pair

checkpoints: './checkpoints/'
model_name: &MODEL_NAME MPR_4degrade
MPR_model: './pretrain_models/MPRnet/model_deblurring.pth'
model_class: MPRnet
resume_train: false 
which_epoch: latest
start_epoch: 0
save_iter: 10000
display_freq: 100
val_freq: 10000
patch_size: 256
gpu: [0,1]
input_nc: 3
output_nc: 3
init_type: xavier
init_gain: 0.02
epoch: 100
# batch_size: 4
is_training: true
load_only_G: false
Distributed: True

train:
  lr_G: 0.0001
  beta1: 0.9
  optimizer: adam
  scheduler: linear

datasets:
  train:
    degrade_num: 4
    data_len: -1
    dataroot_blur: '/home/yjz/hdd/deblur_datasets/Deblur_whole/train_patch' # path to training data
    dataroot_rain: '/home/yjz/hdd/derain_datasets/Derain_whole/train_patch' 
    dataroot_noise: '/home/yjz/hdd/denoise_datasets/Denoise_whole/train_patch' 
    dataroot_light: '/home/yjz/hdd/lowlight_datasets/Lowlight_whole/train_patch' 
    patch_size: 256
    batch_size: 2
    num_workers: 4
    use_shuffle: true
    Distributed: True 
  val:
    val_batch_size: 1
    data_len: 50
    dataroot_blur: '/home/yjz/hdd/deblur_datasets/Deblur_whole/test/GOPRO'    # path to validation data
    dataroot_rain: '/home/yjz/hdd/derain_datasets/Derain_whole/test/Rain100L'    
    dataroot_noise: '/home/yjz/hdd/denoise_datasets/Denoise_whole/test/SIDD'    
    dataroot_light: '/home/yjz/hdd/lowlight_datasets/Lowlight_whole/test'    
    patch_size: 256

model:
  g_name: MPRnet
  d_name: Offset
  use_sigmoid: 0
  norm: 


test:
  result_dir: ./exp_results
  save_dir: *MODEL_NAME
  verbose: True
  test_batch_size: 1
  which_epoch: latest
  dataset_mode: pair
  blur_videos: /home/yjz/datasets/Gopro_1080p/test/**/blur/*.png
  deblur_videos: /home/yjz/datasets/Gopro_1080p/test/**/sharp/*.png
  real_blur_videos: /home/yjz/datasets/S10_blur_set/train/**/*.png





