---
dataset_mode: mix

checkpoints: './checkpoints/MPR_naive'
model_name: &MODEL_NAME MPR_mix_hpc
MPR_model: './pretrain_models/MPRnet/model_deblurring.pth'
model_class: MPRnet
resume_train: False 
which_epoch: latest
start_epoch: 0
save_epoch: 50
display_freq: 100
val_freq: 4
crop_size: 256
gpu: [0,1]
input_nc: 3
output_nc: 3
init_type: xavier
init_gain: 0.02
epoch: 1000
batch_size: 2
is_training: False
iteration_G: 1
load_only_G: false

train:
  lr_G: 0.0001
  beta1: 0.9
  optimizer: adam
  scheduler: linear
  train_dir_blur: '/home/yjz/hdd/deblur_datasets/Deblur_whole/train' # path to training data
  train_dir_rain: '/home/yjz/hdd/derain_datasets/Derain_whole/train' 
  train_dir_noise: '/home/yjz/hdd/denoise_datasets/Denoise_whole/train' 
  

val:
  val_batch_size: 1
  verbose: False
  val_dir_blur: '/home/yjz/hdd/deblur_datasets/Deblur_whole/val'    # path to validation data
  val_dir_rain: '/home/yjz/hdd/derain_datasets/Derain_whole/test/Rain100L'    
  val_dir_noise: '/home/yjz/hdd/denoise_datasets/Denoise_whole/test'    

model:
  g_name: MPRnet
  d_name: Offset
  use_sigmoid: 0
  norm: 


test:
  result_dir: ./exp_results
  save_dir: Mix_blur_noise_iter2
  verbose: True
  test_batch_size: 1
  which_epoch: best
  dataset_mode: mix
  # test_dir: '/home/yjz/hdd/Mixed_datasets/Blur_noise/Gopro_gauss'   
  test_dir: '/home/yjz/Image_deblur/Multitask_restore/exp_results/Mix_blur_noise/mixed/Gopro_gauss'   
